/**
 * LLM Wrapper
 * 
 * Safe wrapper for optional LLM calls.
 * Rules:
 * - Used for topic rewriting, summary improvement, and task decomposition
 * - Never used for decision-making or entity creation
 * - Always returns fallback value if LLM fails or is disabled
 * - No hallucinated entities allowed
 * - No retries, no loops
 */

import config from "../config.js";

/**
 * Attempt an LLM call to rewrite a topic for clarity.
 * Falls back to original topic if LLM is disabled, fails, or returns invalid output.
 * 
 * @param {string} originalTopic - The topic extracted by Input Agent
 * @param {string} intent - The classified intent for context
 * @returns {Promise<string>} - Improved topic or original unchanged
 */
export async function rewriteTopic(originalTopic, intent) {
  if (!originalTopic) return originalTopic;
  if (!config.enable_llm) return originalTopic;
  if (!config.llm.api_key) return originalTopic;

  try {
    const prompt = buildTopicPrompt(originalTopic, intent);
    const response = await callLLM(prompt);

    if (
      typeof response === "string" &&
      response.trim().length > 0 &&
      response.trim().length <= 60
    ) {
      return response.trim();
    }

    return originalTopic;
  } catch {
    return originalTopic;
  }
}

/**
 * Attempt an LLM call to improve a raw summary.
 * Falls back to original summary if LLM is disabled, fails, or returns invalid output.
 * 
 * @param {string} originalSummary - The summary generated by Input Agent
 * @param {string} intent - The classified intent
 * @param {object} entities - The extracted entities
 * @returns {Promise<string>} - Improved summary or original unchanged
 */
export async function improveSummary(originalSummary, intent, entities) {
  if (!originalSummary) return originalSummary;
  if (!config.enable_llm) return originalSummary;
  if (!config.llm.api_key) return originalSummary;

  try {
    const prompt = buildSummaryPrompt(originalSummary, intent, entities);
    const response = await callLLM(prompt);

    if (
      typeof response === "string" &&
      response.trim().length > 0 &&
      response.trim().split(/\s+/).length <= 15
    ) {
      return response.trim();
    }

    return originalSummary;
  } catch {
    return originalSummary;
  }
}

/**
 * Attempt an LLM call to decompose a complex instruction into multiple steps.
 * Falls back to null if LLM is disabled, fails, or returns invalid output.
 * 
 * @param {string} rawText - The original raw input text
 * @param {object} enhancedInput - The enhanced Input Agent output for context
 * @returns {Promise<object|null>} - Decomposition result or null (caller uses rule-based fallback)
 */
export async function decomposeWithLLM(rawText, enhancedInput) {
  if (!rawText) return null;
  if (!config.enable_llm) return null;
  if (!config.llm.api_key) return null;

  const VALID_ACTIONS = ["schedule", "send_email", "create_task", "set_reminder", "escalate"];

  try {
    const prompt = buildDecompositionPrompt(rawText, enhancedInput);
    const response = await callLLM(prompt);

    // Parse JSON from LLM response
    const jsonMatch = response.match(/\[[\s\S]*\]/);
    if (!jsonMatch) return null;

    const actions = JSON.parse(jsonMatch[0]);

    // Validate structure
    if (!Array.isArray(actions) || actions.length === 0) return null;

    const validatedActions = [];
    for (const action of actions) {
      if (
        typeof action === "object" &&
        VALID_ACTIONS.includes(action.action_type) &&
        typeof action.parameters === "object"
      ) {
        validatedActions.push({
          action_type: action.action_type,
          parameters: {
            person: action.parameters.person || null,
            topic: action.parameters.topic || null,
            deadline: action.parameters.deadline || null
          }
        });
      }
    }

    if (validatedActions.length === 0) return null;

    return {
      actions: validatedActions,
      confidence: 0.75
    };
  } catch {
    return null;
  }
}

// ═══════════════════════════════════════
// Prompt Builders
// ═══════════════════════════════════════

function buildTopicPrompt(topic, intent) {
  return [
    "Rewrite the following topic to be clearer and more concise.",
    "Rules: Do NOT add new information. Do NOT change the meaning.",
    "Return ONLY the rewritten topic as plain text, max 60 characters.",
    "",
    `Intent: ${intent}`,
    `Topic: ${topic}`,
    "",
    "Rewritten topic:"
  ].join("\n");
}

function buildSummaryPrompt(summary, intent, entities) {
  return [
    "Improve the readability of this summary. Make it a clear, natural sentence.",
    "Rules: Do NOT add new information. Do NOT change the meaning.",
    "Do NOT exceed 15 words. Return ONLY the improved summary.",
    "",
    `Intent: ${intent}`,
    `Entities: ${JSON.stringify(entities)}`,
    `Summary: ${summary}`,
    "",
    "Improved summary:"
  ].join("\n");
}

function buildDecompositionPrompt(rawText, enhancedInput) {
  return [
    "You are an AI system that breaks a user instruction into separate executable actions.",
    "",
    "STRICT RULES:",
    "- Return ONLY a valid JSON array",
    "- Do NOT include explanations, comments, or extra text",
    "- Do NOT wrap JSON in markdown",
    "- Each action must be separate",
    "- Do NOT merge multiple actions into one",
    "- Use ONLY the provided action types",
    "- If multiple actions exist, list them in correct order",
    "- If only one action exists, return a single-item array",
    "",
    "VALID action_type values:",
    "schedule, send_email, create_task, set_reminder, escalate",
    "",
    "Each object must follow EXACTLY this structure:",
    '{ "action_type": "<string>", "parameters": { "person": "<string|null>", "topic": "<string|null>", "deadline": "<string|null>" } }',
    "",
    "IMPORTANT:",
    "- Do NOT invent new people, topics, or deadlines",
    "- Use only information present in input or context",
    "- If missing, set value to null",
    "",
    `Input: "${rawText}"`,
    `Context intent: ${enhancedInput.intent}`,
    `Context entities: ${JSON.stringify(enhancedInput.entities)}`,
    "",
    "OUTPUT (JSON array only):"
  ].join("\n");
}

// ═══════════════════════════════════════
// LLM Call
// ═══════════════════════════════════════

async function callLLM(prompt) {
  const { provider, api_key, timeout_ms, max_tokens } = config.llm;

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeout_ms);

  try {
    let url, headers, body;

    if (provider === "gemini") {
      url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${api_key}`;
      headers = { "Content-Type": "application/json" };
      body = JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: { maxOutputTokens: max_tokens, temperature: 0.1 }
      });
    } else if (provider === "openai") {
      url = "https://api.openai.com/v1/chat/completions";
      headers = {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${api_key}`
      };
      body = JSON.stringify({
        model: "gpt-3.5-turbo",
        messages: [{ role: "user", content: prompt }],
        max_tokens,
        temperature: 0.1
      });
    } else {
      throw new Error(`Unsupported LLM provider: ${provider}`);
    }

    const response = await fetch(url, {
      method: "POST",
      headers,
      body,
      signal: controller.signal
    });

    if (!response.ok) {
      throw new Error(`LLM API returned ${response.status}`);
    }

    const data = await response.json();

    if (provider === "gemini") {
      return data?.candidates?.[0]?.content?.parts?.[0]?.text || "";
    } else if (provider === "openai") {
      return data?.choices?.[0]?.message?.content || "";
    }

    return "";
  } finally {
    clearTimeout(timeoutId);
  }
}
